apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db-username: cG9zdGdyZXM=
  db-password: cG9zdGdyZXM=
  db-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQGRiLXNlcnZpY2U6NTQzMi9qb3VybmFsX2Ri